services:

  historian:
    image: timebase/historian:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4096m
    hostname: historian
    container_name: historian
    ports:
      - "4511:4511"
      - "4512:4512"
    restart: unless-stopped
    volumes:
      - /opt/docker/timebase/historian:/historian
    environment:
      - Settings=/historian/settings
      - Data=/historian/data
      - Logs=/historian/logs

  explorer:
    image: timebase/explorer:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048m
    hostname: explorer
    container_name: explorer
    ports:
      - "4531:4531"
      - "4532:4532"
    restart: unless-stopped
    volumes:
      - /opt/docker/timebase/explorer:/explorer
    environment:
      - Settings=/explorer/settings
      - Config=/explorer/config
      - Data=/explorer/data
      - Logs=/explorer/logs
 
  simulator:
    image: timebase/collector:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4096m
    hostname: simulator
    container_name: simulator
    ports:
      - "4521:4521"
      - "4522:4522"
    restart: unless-stopped
    volumes:
     - /opt/docker/timebase/simulator:/simulator
    environment:
      - Active=false
      - Settings=/simulator/settings
      - Config=/simulator/config
      - Data=/simulator/data
      - Logs=/simulator/logs


  postgresql:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_super_password
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_super_password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  emqx1:
    image: emqx/emqx:latest
    container_name: emqx1
    restart: unless-stopped    
    environment:
      - EMQX_NAME=emqx1
    ports:
      - "1884:1883"      # MQTT
      - "18083:18083"    # Dashboard
      - "8083:8083"      # WebSocket
      # - "8883:8883"      # TLS         
    volumes:
      - emqx1-data:/opt/emqx/data
      - emqx1-log:/opt/emqx/log

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n-data:/home/node/.n8n      

volumes:
  pg-data:
  pgadmin-data:
  grafana-data:
  emqx1-data:
  emqx1-log:
  n8n-data:

networks:
  default:
    name: otnetwork
